// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  hero: dynamic(() => import("./BannerTop")),
  image: dynamic(() => import("./Image")),
  image_cards: dynamic(() => import("./ImageCards")),
  quote: dynamic(() => import("./CitationBloc")),
  text: dynamic(() => import("./Text")),
  text_with_image: dynamic(() => import("./TextAndImage")),
};
